<script setup lang="ts">
import {ref,computed,onMounted,onUnmounted} from 'vue';
import {Activity,Database,FileText,Settings,ArrowUpRight,ArrowRight,RefreshCw,Plus,Check,AlertCircle,Clock,ChevronDown,ChevronRight,Download,ExternalLink,LogOut,X,Play,Search,ShieldCheck,Layers,Coins,PanelLeftClose} from 'lucide-vue-next';
type Row=Record<string,any>;
const logged=ref(false),ready=ref(false),view=ref('analysis'),overview=ref<Row>({}),datasets=ref<Row[]>([]),jobs=ref<Row[]>([]),reports=ref<Row[]>([]),selected=ref<Row|null>(null),settingsOpen=ref(false),config=ref<Row>({}),notice=ref(''),busy=ref(false),date=ref(''),mode=ref('close'),code=ref(''),assetType=ref('stock'),username=ref('admin'),password=ref(''),loginError=ref(''),evidence=ref<Row|null>(null),review=ref<Row|null>(null),mobileNav=ref(false);
const nav=[{id:'analysis',label:'分析工作台',icon:FileText},{id:'data',label:'数据中心',icon:Database}];
const labels:Row={queued:'等待执行',running:'进行中',succeeded:'已完成',degraded:'部分完成',failed:'失败',cancelled:'已取消',interrupted:'已中断',waiting_close:'等待收盘',skipped_closed:'休市',passed:'已校验',available:'已采集',missing:'未采集',partial:'部分可用',unavailable:'不可用'};
const factorNames:Row={fundamental_catalyst:'基本面催化',industry_cycle:'行业周期',liquidity:'流动性',technical_structure:'技术结构',valuation:'估值',risk:'风险'};
const kindNames:Row={enginecheck:'分析引擎测试',collect:'收盘数据采集',research:'研究分析',supplement:'标的资料采集',gold:'黄金价格采集',demo:'离线演示'};
const activeJobs=computed(()=>jobs.value.filter(j=>['running','queued'].includes(j.status)));
const forecast=computed(()=>selected.value?.output?.forecast);
const pct=(v:any)=>typeof v==='number'?(v>0?'+':'')+v.toFixed(2)+'%':'—';
const fixed=(v:any)=>typeof v==='number'?v.toLocaleString('zh-CN',{maximumFractionDigits:2}):'—';
const time=(v:any)=>v?String(v).replace('T',' ').slice(0,16):'—';
const stateClass=(s:string)=>['passed','available','succeeded'].includes(s)?'good':['failed','interrupted'].includes(s)?'bad':['running','queued'].includes(s)?'working':'muted';
async function api(path:string,method='GET',body?:any){
 const r=await fetch('/api'+path,{method,headers:body!==undefined?{'Content-Type':'application/json'}:{},body:body!==undefined?JSON.stringify(body):undefined});
 let data:any;try{data=await r.json()}catch{throw Error('服务暂不可用，请检查启动状态')}
 if(!r.ok){if(r.status===401)logged.value=false;throw Error(typeof data.detail==='string'?data.detail: data.detail?.map((v:any)=>v.msg).join('；')||'请求失败')};return data;
}
async function load(){
 const [o,d,t,r]=await Promise.all([api('/overview'),api('/datasets'),api('/tasks'),api('/reports')]);overview.value=o;datasets.value=d;jobs.value=t;reports.value=r;if(!date.value)date.value=o.today;if(!selected.value&&r.length){selected.value=await api('/reports/'+r[0].id);review.value=await api('/reviews/'+selected.value!.date);}
}
async function login(){busy.value=true;loginError.value='';try{await api('/login','POST',{username:username.value,password:password.value});logged.value=true;password.value='';await load()}catch(e:any){loginError.value=e.message}finally{busy.value=false}}
async function act(fn:()=>Promise<any>){busy.value=true;notice.value='';try{await fn()}catch(e:any){notice.value=e.message}finally{busy.value=false}}
async function start(kind:string){await act(async()=>{const result=await api('/tasks','POST',{kind,date:date.value||overview.value.today,mode:mode.value,asset_type:assetType.value,code:code.value||null});await load();notice.value='任务已加入队列，可在下方查看进度。';return result})}
async function openSettings(){await act(async()=>{config.value=await api('/settings');config.value.api_key='';config.value.gold_api_key='';config.value.watchText=config.value.watch_codes.join(', ');settingsOpen.value=true})}
async function saveSettings(){await act(async()=>{const body:Row={...config.value,watch_codes:config.value.watchText.split(/[,，\s]+/).filter(Boolean)};delete body.watchText;await api('/settings','PUT',body);settingsOpen.value=false;await load();notice.value='设置已保存。'})}
async function openReport(id:string){await act(async()=>{selected.value=await api('/reports/'+id);review.value=await api('/reviews/'+selected.value!.date);view.value='analysis'})}
async function taskAction(id:string,action:string){await act(async()=>{await api(`/tasks/${id}/${action}`,'POST',{});await load()})}
async function showEvidence(){await act(async()=>{if(selected.value&&view.value==='analysis'){evidence.value={sources:selected.value.context.source_urls,hash:selected.value.data_hash,evidence:selected.value.context.evidence}}else if(overview.value.snapshot_date)evidence.value=await api('/snapshot/'+overview.value.snapshot_date)})}
function download(){if(!selected.value)return;const url=URL.createObjectURL(new Blob([selected.value.markdown],{type:'text/markdown;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=`A股分析_${selected.value.date}.md`;a.click();URL.revokeObjectURL(url)}
async function logout(){await api('/logout','POST',{});logged.value=false;selected.value=null}
let timer:ReturnType<typeof setInterval>;
onMounted(async()=>{try{await api('/session');logged.value=true;await load()}catch{}finally{ready.value=true};timer=setInterval(async()=>{if(logged.value&&!busy.value){try{await load()}catch{}}},4000)});
onUnmounted(()=>clearInterval(timer));
</script>

<template>
 <div v-if="!ready" class="boot">正在连接本地工作台…</div>
 <main v-else-if="!logged" class="login-page">
  <div class="login-story"><div class="brand"><span class="brand-mark">A</span><strong>A股分析平台</strong></div><div><span class="eyebrow">每日研究 · 有据可查</span><h1>先看数据，<br>再作判断。</h1><p>把行情、证据与每一次判断放在一起。<br>认真分析，也认真复盘。</p></div><span class="fine">独立研究工具 · 不构成投资建议</span></div>
  <form class="login-form" @submit.prevent="login"><span class="small-label">欢迎回来</span><h2>登录研究工作台</h2><p class="subtle">使用本机启动时生成的管理员账号。</p><label>账号<input v-model="username" autocomplete="username" required></label><label>密码<input v-model="password" type="password" autocomplete="current-password" minlength="6" maxlength="100" required></label><p v-if="loginError" role="alert" class="error">{{loginError}}</p><button class="primary full" :disabled="busy">{{busy?'正在登录…':'进入工作台'}}<ArrowRight :size="17"/></button><p class="login-help">首次登录密码保存在本机<br><code>runtime/admin-credentials.txt</code></p></form>
 </main>
 <div v-else class="shell">
  <aside class="sidebar" :class="{visible:mobileNav}"><div class="brand"><span class="brand-mark">A</span><div><strong>A股分析平台</strong><small>研究 · 证据 · 复盘</small></div></div><div class="nav-label">研究空间</div><nav><button v-for="n in nav" :key="n.id" :class="{active:view===n.id}" @click="view=n.id;mobileNav=false"><component :is="n.icon" :size="19"/>{{n.label}}<ChevronRight v-if="view===n.id" :size="15" class="nav-arrow"/></button></nav><div class="side-note"><span class="dot" :class="overview.worker_online?'green':'grey'"></span>{{overview.worker_online?'执行服务在线':'执行服务离线'}}<small>本机工作空间 · 数据独立保存</small></div><div class="sidebar-bottom"><button @click="openSettings"><Settings :size="18"/>设置</button><button @click="logout"><LogOut :size="18"/>退出登录</button><div class="user"><span>研</span><div>个人研究空间<small>不构成投资建议</small></div></div></div></aside>
  <div class="body"><header class="topbar"><div><button class="icon-button mobile-toggle" aria-label="打开导航" @click="mobileNav=!mobileNav"><Layers :size="19"/></button><span class="crumb">工作空间</span><ChevronRight :size="14"/><strong>{{view==='analysis'?'分析工作台':'数据中心'}}</strong></div><div class="top-right"><span class="quiet-tag">A 股</span><span class="subtle">{{overview.today}} · 上海时间</span></div></header>
   <div v-if="notice" class="toast" role="status"><AlertCircle :size="17"/><span>{{notice}}</span><button class="icon-button" aria-label="关闭提示" @click="notice=''"><X :size="16"/></button></div>
   <div v-if="!overview.worker_online" class="service-warning"><AlertCircle :size="16"/>后台执行服务离线。已保存的报告可正常查看，新任务将在服务恢复后执行。</div>
   <main class="workspace">
    <template v-if="view==='analysis'">
     <div class="page-heading"><div><span class="eyebrow">每日研究</span><h1>分析工作台</h1><p>让每个判断有依据，让每次预测可复盘。</p></div><button class="secondary" @click="start('demo')" :disabled="busy"><Play :size="15"/>体验离线演示</button></div>
     <section class="research-form" aria-label="创建研究任务"><div class="segmented"><button :class="{chosen:mode==='close'}" @click="mode='close'">收盘分析</button><button :class="{chosen:mode==='instrument'}" @click="mode='instrument'">指定标的</button></div><div class="research-controls"><label class="compact">研究日期<input v-model="date" type="date" :max="overview.today" required></label><template v-if="mode==='instrument'"><label class="compact">类型<select v-model="assetType"><option value="stock">股票</option><option value="index">指数</option></select></label><label class="compact grow">标的代码<input v-model="code" inputmode="numeric" maxlength="6" placeholder="例如 600519"></label></template><div v-else class="scope-note"><Layers :size="17"/>大盘 · 板块 · 五股 · 黄金 · 昨日复盘</div><button class="primary" @click="start('research')" :disabled="busy || !overview.worker_online"><Plus :size="17"/>生成分析</button></div><div class="form-foot"><ShieldCheck :size="14"/><span>{{overview.analysis_engine==='codex_cli'?'Codex CLI':'模型 API'}} · 分析前校验数据，完成后审阅证据。历史日期仅作研究，不补造预测。</span><button v-if="!overview.model_configured" class="text-button" @click="openSettings">配置模型 <ArrowUpRight :size="13"/></button></div></section>
     <section v-if="overview.indices?.length" class="market-strip"><div class="strip-top"><span>最近归档行情</span><span>{{overview.snapshot_date}} <em v-if="overview.snapshot_date!==overview.today">历史数据</em></span></div><div class="indices"><div v-for="i in overview.indices" :key="i.code"><span>{{i.name}}</span><strong>{{fixed(i.close)}}</strong><small :class="i.pct>0?'up':i.pct<0?'down':''">{{pct(i.pct)}} <ArrowUpRight v-if="i.pct>0" :size="12"/></small></div></div></section>
     <div class="section-title"><h2>研究报告 <span>{{reports.length}}</span></h2><span class="subtle">报告与证据一起留存</span></div>
     <div class="report-workspace"><aside class="report-list"><div class="list-caption">最近报告</div><button v-for="r in reports" :key="r.id" :class="{selected:selected?.id===r.id}" @click="openReport(r.id)"><div><span class="report-type">{{r.mode==='demo'?'演示':r.mode==='instrument'?'标的研究':'收盘研究'}}</span><span class="report-date">{{r.date}}</span></div><strong>{{r.title}}</strong><p>{{r.summary}}</p><small><span class="dot" :class="r.incomplete?'amber':'green'"></span>{{r.status}}</small></button><div v-if="!reports.length" class="list-empty"><FileText :size="22"/><p>还没有分析报告</p><small>先采集数据，再生成第一份研究。</small></div></aside>
      <article v-if="selected" class="report-detail"><div class="report-meta"><span>{{selected.date}} · {{selected.mode==='demo'?'离线演示':'研究归档'}}</span><div><button class="icon-button" title="查看证据" aria-label="查看证据" @click="showEvidence"><Database :size="17"/></button><button class="icon-button" title="下载报告" aria-label="下载报告" @click="download"><Download :size="17"/></button></div></div><h2>{{selected.output.title}}</h2><div class="report-status"><span class="pill" :class="selected.mode==='demo'?'muted':'good'">{{selected.status}}</span><span v-if="selected.incomplete" class="pill muted">研究资料不完整</span></div><p class="report-summary">{{selected.output.summary}}</p><section v-for="(s,i) in selected.output.sections" :key="i"><h3>{{s.heading}}</h3><p>{{s.text}}</p><button class="evidence-link" @click="showEvidence"><Layers :size="13"/>{{s.evidence_ids?.length||0}} 项证据 <ArrowUpRight :size="13"/></button></section>
       <section v-if="forecast"><h3>下一交易日预测 <small>{{forecast.next_trade_date}}</small></h3><div class="table-wrap"><table><thead><tr><th>标的</th><th>预测区间</th><th>上涨 / 震荡 / 下跌</th></tr></thead><tbody><template v-for="g in ['indices','sectors','watch_pool']" :key="g"><tr v-for="f in forecast[g]" :key="g+f.code"><td><strong>{{f.name}}</strong><small>{{f.code}}</small></td><td>{{f.lower}}% ～ {{f.upper}}%</td><td>{{f.probabilities.up}} / {{f.probabilities.flat}} / {{f.probabilities.down}}%</td></tr></template></tbody></table></div><details v-for="g in ['indices','sectors','watch_pool']" :key="g"><summary>{{g==='indices'?'指数':g==='sectors'?'板块':'五股'}}观点与失效条件</summary><div v-for="f in forecast[g]" :key="f.code" class="forecast-note"><strong>{{f.name}}</strong><p>{{f.week_view||f.week_range}}</p><p>失效条件：{{f.invalidation}}</p><p v-if="f.watch_condition">关注条件：{{f.watch_condition}}</p><div v-if="f.factors"><p v-for="(factor,key) in f.factors" :key="key">{{factorNames[key]||key}}：{{factor.conclusion}}</p></div></div></details></section>
       <section><h3>昨日预测与今日实际</h3><p v-if="selected.mode!=='demo' && overview.summary?.overall?.sample_count">累计 {{overview.summary.overall.sample_count}} 项评价 · 方向命中 {{fixed(overview.summary.overall.direction_hit_rate*100)}}% · 区间命中 {{fixed(overview.summary.overall.range_hit_rate*100)}}% · MAE {{fixed(overview.summary.overall.mean_absolute_error)}} 个百分点</p><p>{{selected.context.ledger_note}}</p><div v-if="review?.records?.length" class="table-wrap"><table><thead><tr><th>标的</th><th>预测中点</th><th>实际</th><th>偏差</th><th>状态</th></tr></thead><tbody><tr v-for="r in review.records" :key="r.asset_type+r.asset_code"><td>{{r.asset_name||r.asset_code}}</td><td>{{r.midpoint??'—'}}</td><td>{{r.actual_pct??'—'}}</td><td>{{r.error??'—'}}</td><td>{{r.status==='evaluated'?'已评价':r.reason}}</td></tr></tbody></table></div></section>
       <section><h3>黄金价格</h3><p>{{selected.output.gold?.text||'没有独立黄金证据，暂不作判断。'}}</p><small class="subtle">黄金本体独立研究，尚未纳入正式评分。</small></section><section class="risk-block"><h3><AlertCircle :size="17"/>风险与失效条件</h3><ul><li v-for="r in selected.output.risks" :key="r">{{r}}</li></ul></section><footer class="report-footer">不构成投资建议 · {{selected.engine==='codex_cli'?'Codex CLI · ':''}}{{time(selected.created_at)}}</footer>
      </article>
      <article v-else class="report-placeholder"><div class="paper-symbol"><FileText :size="33" :stroke-width="1.3"/></div><h2>研究，从一份可靠的数据开始。</h2><p>选择一份报告，查看结论、证据与复盘。<br>也可以先运行离线演示，了解整个工作流程。</p><button class="text-button" @click="view='data'">前往数据中心 <ArrowRight :size="16"/></button><div class="three-steps"><span><Database :size="16"/>采集与校验</span><ChevronRight :size="13"/><span><FileText :size="16"/>分析与审阅</span><ChevronRight :size="13"/><span><Activity :size="16"/>逐日复盘</span></div></article>
     </div>
    </template>
    <template v-else>
     <div class="page-heading"><div><span class="eyebrow">研究的起点</span><h1>数据中心</h1><p>知道数据从哪里来，也知道它能支持什么判断。</p></div><button class="primary" @click="start('collect')" :disabled="busy || !overview.worker_online"><RefreshCw :size="16"/>采集收盘数据</button></div>
     <div class="data-summary"><div><span>正式快照</span><strong>{{overview.snapshot_count||0}}<small>份</small></strong></div><div><span>最新归档</span><strong class="date-value">{{overview.snapshot_date||'尚无数据'}}</strong></div><div><span>正式预测</span><strong>{{overview.forecast_count||0}}<small>份</small></strong></div><div><span>交易日历</span><strong>{{overview.calendar_year}}<small>年</small></strong></div></div>
     <div class="data-toolbar"><label class="inline-label">采集日期 <input type="date" v-model="date" :max="overview.today"></label><button class="text-button" @click="showEvidence" :disabled="!overview.snapshot_date"><Layers :size="15"/>查看最近快照证据</button></div>
     <div class="table-wrap dataset-table"><table><thead><tr><th>数据集</th><th>来源</th><th>归档 / 请求日期</th><th>状态</th><th>范围与说明</th></tr></thead><tbody><tr v-for="d in datasets" :key="d.key"><td><span class="dataset-name"><component :is="d.key==='gold'?Coins:Database" :size="17"/>{{d.name}}</span></td><td>{{d.provider}}</td><td>{{d.as_of||'—'}}</td><td><span class="pill" :class="stateClass(d.status)">{{labels[d.status]||d.status}}</span></td><td class="dataset-note">{{d.note}} <button class="text-button" @click="act(async()=>{evidence=await api('/datasets/'+d.key)})">查看资料</button></td></tr></tbody></table></div>
     <div class="collection-panels"><section><div class="section-title"><h2>按标的补充资料</h2><span class="subtle">近 250 个交易日</span></div><p class="subtle">补充历史行情、财务摘要和相关新闻。缺失的数据会单独标明。</p><div class="inline-form"><select v-model="assetType" aria-label="标的类型"><option value="stock">股票</option><option value="index">指数</option></select><input v-model="code" placeholder="六位股票或指数代码" maxlength="6" aria-label="标的代码"><button class="secondary" @click="start('supplement')" :disabled="busy || !overview.worker_online">采集资料 <ArrowRight :size="15"/></button></div></section><section><div class="section-title"><h2>黄金本体</h2><Coins :size="19"/></div><p class="subtle">国际现货 XAU/USD 与上金所 Au99.99，保留各自时间与单位。</p><button class="secondary" @click="start('gold')" :disabled="busy || !overview.worker_online"><RefreshCw :size="15"/>更新黄金价格</button></section></div>
     <details v-if="overview.missing_dates?.length" class="gap-note"><summary><AlertCircle :size="16"/>有 {{overview.missing_dates.length}} 个交易日缺少正式快照 <ChevronDown :size="15"/></summary><p>历史缺口如实保留，不用当前报价或事后预测补齐。</p><p>{{overview.missing_dates.join('、')}}</p></details>
    </template>
    <section class="tasks-section"><div class="section-title"><h2>任务记录 <span v-if="activeJobs.length">{{activeJobs.length}} 项执行中</span></h2><span class="subtle">进度自动更新</span></div><div v-if="!jobs.length" class="task-empty"><Clock :size="18"/>采集和分析任务会记录在这里。</div><div v-for="t in jobs.slice(0,8)" :key="t.id" class="task-row"><span class="task-icon" :class="stateClass(t.status)"><RefreshCw v-if="t.status==='running'" class="spin" :size="17"/><Check v-else-if="t.status==='succeeded'" :size="17"/><Clock v-else :size="17"/></span><div class="task-description"><strong>{{kindNames[t.kind]}} <small>{{t.payload.code||t.payload.date}}</small></strong><p>{{t.error||t.stage}}</p></div><span class="pill" :class="stateClass(t.status)">{{labels[t.status]||t.status}}</span><time>{{time(t.created_at)}}</time><button v-if="t.result?.report_id" class="text-button" @click="openReport(t.result.report_id)">查看报告<ArrowUpRight :size="13"/></button><button v-else-if="['running','queued'].includes(t.status)" class="text-button" @click="taskAction(t.id,'cancel')">取消</button><button v-else class="text-button" @click="taskAction(t.id,'retry')">重试</button></div></section>
    <footer class="workspace-footer"><span>A股分析平台 · 独立研究空间</span><span>数据有时效，判断有条件。不构成投资建议。</span></footer>
   </main>
  </div>
 </div>
 <div v-if="settingsOpen" class="overlay" @click.self="settingsOpen=false"><section class="drawer" role="dialog" aria-modal="true" aria-labelledby="settings-title"><header><div><span class="eyebrow">工作空间设置</span><h2 id="settings-title">连接数据与模型</h2></div><button class="icon-button" aria-label="关闭设置" @click="settingsOpen=false"><X :size="20"/></button></header><form @submit.prevent="saveSettings"><h3>分析引擎</h3><label>执行方式<select v-model="config.analysis_engine"><option value="api">模型 API</option><option value="codex_cli">本机 Codex CLI</option></select></label><template v-if="config.analysis_engine==='codex_cli'"><p class="subtle">由 Mac 上的 Codex 完成分析，使用本机登录。电脑与本机执行服务需要保持运行。</p><p role="status" :class="overview.codex_status?.ready?'good-text':'subtle'">{{overview.codex_status?.message||'正在检查本机服务'}} <small>{{overview.codex_status?.version}}</small></p><label>Codex 模型名称<input v-model="config.codex_model" placeholder="留空使用 CLI 内置默认模型"><small>使用独立的只读执行配置，不加载个人插件、工具及项目指令。</small></label><label>每次执行最长秒数<input v-model.number="config.codex_timeout" type="number" min="30" max="900"></label></template><template v-else><p class="subtle">支持兼容 Chat Completions 的 JSON 输出接口。密钥只保存在本机服务端。</p><label>服务地址<input v-model="config.model_base_url" required placeholder="https://api.example.com/v1"></label><label>模型名称<input v-model="config.model_name" required></label><label>API 密钥 <span v-if="config.api_key_configured" class="good-text">已配置，留空保留</span><input v-model="config.api_key" type="password" autocomplete="new-password" placeholder="输入服务商提供的 API Key"></label></template><div class="form-grid"><label v-if="config.analysis_engine==='api'">每次最大输出 Token<input v-model.number="config.max_output_tokens" type="number" min="1000" max="16000"></label><label>单任务最多调用<input v-model.number="config.max_calls" type="number" min="2" max="3"></label></div><h3>研究范围</h3><label>五股关注池<input v-model="config.watchText" required><small>五个代码，用逗号分隔；已有正式预测优先延续其关注池。</small></label><label>GoldAPI 密钥 <span v-if="config.gold_api_key_configured" class="good-text">已配置</span><input v-model="config.gold_api_key" type="password" autocomplete="new-password" placeholder="可选，用于国际现货黄金"></label><h3>收盘计划</h3><label class="check-label"><input type="checkbox" v-model="config.schedule_enabled">交易日自动生成收盘分析</label><label>上海时间<input type="time" v-model="config.schedule_time" min="15:15"></label><p class="subtle">需要电脑与执行服务保持运行。休眠期间不补造收盘快照。</p><button class="primary full" :disabled="busy">保存设置 <Check :size="17"/></button><button type="button" class="secondary full" :disabled="busy" @click="start('enginecheck')">测试已保存的分析引擎</button><p class="subtle">测试会发起一次简短模型请求，消耗所选服务的额度；修改后请先保存。</p><p v-if="jobs.find(j=>j.kind==='enginecheck')" role="status">最近测试：{{jobs.find(j=>j.kind==='enginecheck')?.error||jobs.find(j=>j.kind==='enginecheck')?.stage}}</p></form></section></div>
 <div v-if="evidence" class="overlay" @click.self="evidence=null"><section class="drawer evidence-drawer" role="dialog" aria-modal="true" aria-labelledby="evidence-title"><header><div><span class="eyebrow">可追溯资料</span><h2 id="evidence-title">数据与证据</h2></div><button class="icon-button" aria-label="关闭证据" @click="evidence=null"><X :size="20"/></button></header><p class="subtle">保留数据日期、来源与质量状态。历史导入未包含的原始响应不会补造。</p><pre>{{JSON.stringify(evidence,null,2)}}</pre></section></div>
</template>
